package com.jbk.hibernate;
// Generated Apr 23, 2020 11:49:24 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Student2 generated by hbm2java
 */
@Entity
@Table(name = "student2", catalog = "test123")
public class Student2 implements java.io.Serializable {

	private int id;
	private String name;
	private int contact;
	private String city;

	public Student2() {
	}

	public Student2(int id, String name, int contact, String city) {
		this.id = id;
		this.name = name;
		this.contact = contact;
		this.city = city;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "contact", nullable = false)
	public int getContact() {
		return this.contact;
	}

	public void setContact(int contact) {
		this.contact = contact;
	}

	@Column(name = "city", nullable = false, length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

}
